### ISSUE TITLE
Add A "Golden Image" SIMD Environment + Initial Release

### ISSUE THREAD

**Issue by bonedaddy** [teamscanworks/breaker#4]
# Overview

To ease unit + integration testing, we should create a golden image of a simd environment that has been properly configured.

# Tasks

- [x] Add template proposal draft for circuit breaker authorization of test account
- [x] Fix sequence number of factory falling out of sync
- [x] Transaction sending through API is racey leading to invalid sequence numbers
- [x] Working API server and client packages
